-- AlterTable: Add personal information fields to Member
ALTER TABLE "Member" ADD COLUMN "lastNameKana" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "firstNameKana" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "jobResponsibility" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "jobGrade" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "groupType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "spec" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "birthDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "age" INTEGER;
ALTER TABLE "Member" ADD COLUMN "mandatoryRetirementDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "salaryRegion" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" ADD COLUMN "isInactive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN "returnDate" TEXT NOT NULL DEFAULT '';
